Traceback (most recent call last):
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import math
import os

import pytorch_lightning as pl
import torch
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks.progress import TQDMProgressBar
from pytorch_lightning.loggers import TensorBoardLogger
from ray import tune
from ray.tune import CLIReporter
from ray.tune.integration.pytorch_lightning import (
    TuneReportCallback,
    TuneReportCheckpointCallback,
)
from ray.tune.schedulers import ASHAScheduler, PopulationBasedTraining
from torch.nn import functional as F
from torch.utils.data import DataLoader, random_split
from torchvision import transforms
from torchvision.datasets import MNIST
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/ray/tune/progress_reporter.py:39[0m, in [0;36m<module>[0;34m[0m
[1;32m     38[0m [38;5;28;01mtry[39;00m:
[0;32m---> 39[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtabulate[39;00m [38;5;28;01mimport[39;00m tabulate
[1;32m     40[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

[0;31mModuleNotFoundError[0m: No module named 'tabulate'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [13][0m, in [0;36m<cell line: 9>[0;34m()[0m
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpytorch_lightning[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcallbacks[39;00m[38;5;21;01m.[39;00m[38;5;21;01mprogress[39;00m [38;5;28;01mimport[39;00m TQDMProgressBar
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpytorch_lightning[39;00m[38;5;21;01m.[39;00m[38;5;21;01mloggers[39;00m [38;5;28;01mimport[39;00m TensorBoardLogger
[0;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m [38;5;28;01mimport[39;00m tune
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m [38;5;28;01mimport[39;00m CLIReporter
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mintegration[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpytorch_lightning[39;00m [38;5;28;01mimport[39;00m (
[1;32m     12[0m     TuneReportCallback,
[1;32m     13[0m     TuneReportCheckpointCallback,
[1;32m     14[0m )

File [0;32m/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/ray/tune/__init__.py:2[0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01merror[39;00m [38;5;28;01mimport[39;00m TuneError
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m [38;5;28;01mimport[39;00m run_experiments, run
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01msyncer[39;00m [38;5;28;01mimport[39;00m SyncConfig
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexperiment[39;00m [38;5;28;01mimport[39;00m Experiment

File [0;32m/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/ray/tune/tune.py:22[0m, in [0;36m<module>[0;34m[0m
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexperiment[39;00m [38;5;28;01mimport[39;00m Experiment, convert_to_experiment_list
[1;32m     21[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlogger[39;00m [38;5;28;01mimport[39;00m Logger
[0;32m---> 22[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mprogress_reporter[39;00m [38;5;28;01mimport[39;00m (
[1;32m     23[0m     detect_reporter,
[1;32m     24[0m     ProgressReporter,
[1;32m     25[0m     JupyterNotebookReporter,
[1;32m     26[0m )
[1;32m     27[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mray_trial_executor[39;00m [38;5;28;01mimport[39;00m RayTrialExecutor
[1;32m     28[0m [38;5;28;01mfrom[39;00m [38;5;21;01mray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtune[39;00m[38;5;21;01m.[39;00m[38;5;21;01mregistry[39;00m [38;5;28;01mimport[39;00m get_trainable_cls

File [0;32m/usr/share/miniconda/envs/swd8_intro_ml/lib/python3.9/site-packages/ray/tune/progress_reporter.py:41[0m, in [0;36m<module>[0;34m[0m
[1;32m     39[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtabulate[39;00m [38;5;28;01mimport[39;00m tabulate
[1;32m     40[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m---> 41[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     42[0m         [38;5;124m"[39m[38;5;124mray.tune in ray > 0.7.5 requires [39m[38;5;124m'[39m[38;5;124mtabulate[39m[38;5;124m'[39m[38;5;124m. [39m[38;5;124m"[39m
[1;32m     43[0m         [38;5;124m"[39m[38;5;124mPlease re-run [39m[38;5;124m'[39m[38;5;124mpip install ray[tune][39m[38;5;124m'[39m[38;5;124m or [39m[38;5;124m"[39m
[1;32m     44[0m         [38;5;124m"[39m[38;5;124m'[39m[38;5;124mpip install ray[rllib][39m[38;5;124m'[39m[38;5;124m.[39m[38;5;124m"[39m
[1;32m     45[0m     )
[1;32m     47[0m [38;5;28;01mtry[39;00m:
[1;32m     48[0m     class_name [38;5;241m=[39m get_ipython()[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m

[0;31mImportError[0m: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.
ImportError: ray.tune in ray > 0.7.5 requires 'tabulate'. Please re-run 'pip install ray[tune]' or 'pip install ray[rllib]'.

